services:
  image-fusion-app:
    image: tomatom4to/image-fusion:latest
    container_name: image-fusion-app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    expose:
      - "3000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt        # 인증서 파일 저장소
      - ./certbot/www:/var/www/certbot         # 인증용 챌린지 파일 저장소
    depends_on:
      - image-fusion-app
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # 12시간마다 자동으로 갱신을 시도하는 명령어
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"